#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=32
#PBS -N split_lib
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

time core_diversity_analyses.py -i ~/2018_02_smb/SeqPrep_joined/OTUs/otu_table.biom -o ~/2018_02_smb/Core1 -m ~/2018_02_smb/map2018.tsv -e 33878 -t ~/SILVA_128_QIIME_release/trees/97/97_otus.tre 

source deactivate 
  
