#!/bin/bash --login
#PBS -l walltime=03:00:00
#PBS -l select=1:ncpus=56
#PBS -N Open_GG_Core_diversity_analyses
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
module load R-3.3.1-gcc-6.2.0-zjrjm3s
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1

time compare_categories.py --method anosim \
-i ~/2018_02_smb/Core/bdiv_even33878/unweighted_unifrac_dm.txt \
-m ~/2018_02_smb/map2018.tsv \
-c SampleNitrogen \
-o ~/2018_02_smb/Core/Compare \
-n 999

source deactivate
