#!/bin/bash --login 
#PBS -l walltime=03:00:00
#PBS -l select=1:ncpus=56
#PBS -N Open_GG_Core_diversity_analyses
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1

time filter_otus_from_otu_table.py \
-i ~/2018_02_smb/Core/taxa_plots/table_mc33878_sorted_L2.biom \
-o ~/2018_02_smb/otu10.biom \
--min_count_fraction 0.01

source deactivate
