#!/bin/bash --login
#PBS -l walltime=03:00:00
#PBS -l select=1:ncpus=56
#PBS -N Open_GG_Core_diversity_analyses
#PBS -A d411-training
cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
echo "loading virtualenv"
source activate qiime1

time group_significance.py -i ~/2018_02_smb/Core/summarytable/otu_table_L2.biom \
-m ~/2018_02_smb/map2018.tsv \
-c SampleVegetation \
-o ~/2018_02_smb/Core/Group_Significance/SampleVegetation.tsv

source deactivate

