#!/bin/bash --login
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=32
#PBS -N split_lib
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# picking OTUs                                                                         
echo "Picking OTUs with closed reference"
time pick_closed_reference_otus.py -i ~/2018_02_smb/SeqPrep_joined/demultiplex_q20/seqs.fna -o OTUs -r ~/SILVA_128_QIIME_release/rep_set/rep_set_16S_only/97/97_otus_16S.fasta -t ~/SILVA_128_QIIME_release/taxonomy/16S_only/97/majority_taxonomy_all_levels.txt -O 16  -a

source deactivate
