#!/bin/bash --login
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=32
#PBS -N split_lib
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

#splitting libraries
echo "splitting libraries at Q20"
time split_libraries_fastq.py \
-m ~/2018_02_smb/map2018.tsv \
-i ~/2018_02_smb/SeqPrep_joined/seqprep_assembled.fastq.gz \
-b ~/2018_02_smb/SeqPrep_joined/seqprep_assembled.fastq_barcodes.fastq \
-o demultiplex_q20 \
-q 19 \
--barcode_type 12 \
--rev_comp_barcode \
--rev_comp_mapping_barcodes

source deactivate
