#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=32
#PBS -N split_lib
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2

# loading virtualenv
echo "loading virtualenv"
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

biom summarize-table -i ~/2018_02_smb/SeqPrep_joined/OTUs/otu_table.biom -o ~/2018_02_smb/SeqPrep_joined/OTUs/summary.txt

source deactivate

